### ISSUE TITLE
Crash from creeper

### ISSUE THREAD

**Issue by Tukanen** [ExterminatorJeff/UndergroundBiomes#15]
UndergroundBiomesConstructs-1.7.2-0.5e
not sure if it still does it in the H version...

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 24-04-14 19:11
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.ubBlock(UBStairsBase.java:97)
    at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.getExplosionResistance(UBStairsBase.java:156)
    at net.minecraft.entity.Entity.func_145772_a(Entity.java:2072)
    at net.minecraft.world.Explosion.func_77278_a(Explosion.java:89)
    at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:898)
    at net.minecraft.world.World.func_72876_a(World.java:2352)
    at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:197)
    at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:116)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:659)
    at net.minecraft.world.World.func_72870_g(World.java:1983)
    at net.minecraft.world.World.func_72939_s(World.java:1836)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:500)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:616)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:665)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.ubBlock(UBStairsBase.java:97)
    at exterminatorJeff.undergroundBiomes.constructs.block.UBStairsBase.getExplosionResistance(UBStairsBase.java:156)
    at net.minecraft.entity.Entity.func_145772_a(Entity.java:2072)
    at net.minecraft.world.Explosion.func_77278_a(Explosion.java:89)
    at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:898)
    at net.minecraft.world.World.func_72876_a(World.java:2352)
    at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:197)
    at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:116)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:659)
    at net.minecraft.world.World.func_72870_g(World.java:1983)

-- Entity being ticked --
Details:
    Entity Type: Creeper (net.minecraft.entity.monster.EntityCreeper)
    Entity ID: 127739
    Entity Name: Creeper
    Entity's Exact location: 3759,61, 92,00, 4996,49
    Entity's Block location: World: (3759,92,4996), Chunk: (at 15,5,4 in 234,312; contains blocks 3744,0,4992 to 3759,255,5007), Region: (7,9; contains chunks 224,288 to 255,319, blocks 3584,0,4608 to 4095,255,5119)
    Entity's Momentum: 0,00, -0,08, 0,00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1836)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:500)

-- Affected level --
Details:
    Level name: world
    All players: 2 total; [EntityPlayerMP['Tarinah'/57228, l='world', x=3654,38, y=63,00, z=5073,34], EntityPlayerMP['Tukanen'/70037, l='world', x=3760,05, y=93,50, z=4995,16]]
    Chunk stats: ServerChunkCache: 1315 Drop: 0
    Level seed: -766001230336385664
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-96,64,844), Chunk: (at 0,4,12 in -6,52; contains blocks -96,0,832 to -81,255,847), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 3177970 game time, 1742326 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 163844 (now: false), thunder time: 94200 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:616)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:665)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1610263040 bytes (1535 MB) / 2061631488 bytes (1966 MB) up to 2061631488 bytes (1966 MB)
    JVM Flags: 38 total; -Xms2048m -Xmx2048m -XX:PermSize=256m -XX:ReservedCodeCacheSize=512m -XX:NewRatio=4 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:MaxGCPauseMillis=20 -XX:GCPauseIntervalMillis=250 -XX:MaxGCMinorPauseMillis=7 -XX:+CMSClassUnloadingEnabled -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:+BindGCTaskThreadsToCPUs -XX:+TieredCompilation -XX:Tier0ProfilingStartPercentage=0 -XX:Tier3InvocationThreshold=3 -XX:Tier3MinInvocationThreshold=2 -XX:Tier3CompileThreshold=2 -XX:Tier3BackEdgeThreshold=10 -XX:Tier4InvocationThreshold=4 -XX:Tier4MinInvocationThreshold=3 -XX:Tier4CompileThreshold=2 -XX:Tier4BackEdgeThreshold=8 -XX:TieredCompileTaskTimeout=5000 -XX:Tier3DelayOn=50 -XX:Tier3DelayOff=25 -XX:+UseFastEmptyMethods -XX:-DontCompileHugeMethods -XX:+AlwaysCompileLoopMethods -XX:+CICompilerCountPerCPU -XX:+UseStringCache -XX:+UseNUMA
    AABB Pool Size: 6980 (390880 bytes; 0 MB) allocated, 5714 (319984 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.01-pre FML v7.2.156.1060 Minecraft Forge 10.12.1.1060 21 mods loaded, 21 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.156.1060} [Forge Mod Loader](forge-1.7.2-10.12.1.1060-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.1.1060} [Minecraft Forge](forge-1.7.2-10.12.1.1060-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BattleTowers{1.4.5} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.6.3} [BiblioCraft](BiblioCraft[1.6.3][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.762-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.1.2} [Carpenter's Blocks](Carpenter's Blocks v3.1.2 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{3.2.0.dev.R1} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DragonMounts{r37} [Dragon Mounts](dragonmount_r37_mc1.7.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.2.0.dev.R1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InfernalMobs{1.4.8} [Infernal Mobs](InfernalMobs-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.2-124.8c69232} [Mantle](Mantle-1.7.2-0.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morpheus{1.7.2-1.3} [Morpheus](morpheus-1.7.2-1.3.38.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.2-1.6.0.jenkins455} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.0.8} [Baubles](Baubles-1.7.2-1.0.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.1.10} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{1.7.2-48.583e8f7} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UndergroundBiomes{0.5} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.5e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 4072 (228032 bytes; 0 MB) allocated, 3499 (195944 bytes; 0 MB) used
    Player Count: 2 / 20; [EntityPlayerMP['Tarinah'/57228, l='world', x=3654,38, y=63,00, z=5073,34], EntityPlayerMP['Tukanen'/70037, l='world', x=3760,05, y=93,50, z=4995,16]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Zeno410** [comment]
That should be fixed in later versions. Unfortunately I can't get into either Curse or Minecraft forum right now due to a server problem. Current version attached.

-----Original Message-----
